"""Generate the docs Reference pages from the live code — the single source of truth.

    uv run python scripts/gen_reference.py

Writes ``docs/src/content/docs/reference/{cli,commands,config,tools}.md`` from the Typer app, the
chat-command registry, the config schema, and the tool registry — so the reference never drifts
from the code. ``tests/unit/test_docs_fresh.py`` re-runs this into a temp dir and diffs, failing CI
if a generated page is stale or hand-edited.
"""

from __future__ import annotations

import inspect
from pathlib import Path

REF_DIR = Path(__file__).resolve().parent.parent / "docs" / "src" / "content" / "docs" / "reference"

_GENERATED = "<!-- GENERATED by scripts/gen_reference.py — do not edit by hand. -->"


def _page(title: str, description: str, body: str) -> str:
    front = f"---\ntitle: {title}\ndescription: {description}\n---\n"
    return f"{front}\n{_GENERATED}\n\n{body.rstrip()}\n"


def gen_cli() -> str:
    # NB: typer vendors its own click fork (typer._click), so `isinstance(cmd, click.Group)` is
    # False here. Detect groups by their `.commands` dict and params by `param_type_name`.
    import typer.main

    from gaia.cli import app

    root = typer.main.get_command(app)
    lines: list[str] = [
        "The `gaia` command-line interface. Run `gaia --help` or `gaia <group> --help` for the "
        "live version of any of these.\n",
    ]

    def render(cmd: object, name_path: list[str], level: int) -> None:
        full = " ".join(["gaia", *name_path])
        heading = "#" * level
        subcommands = getattr(cmd, "commands", None)
        help_text = (getattr(cmd, "help", None) or "").strip()
        lines.append(f"{heading} `{full}`\n")
        if help_text:
            lines.append(help_text.split("\n")[0] + "\n")
        if subcommands:  # a group → recurse into its subcommands
            for sub in sorted(subcommands):
                render(subcommands[sub], [*name_path, sub], min(level + 1, 4))
            return
        params = getattr(cmd, "params", [])
        args = [p for p in params if p.param_type_name == "argument"]
        opts = [p for p in params if p.param_type_name == "option" and p.name != "help"]
        usage = full + "".join(f" <{a.name}>" for a in args) + (" [options]" if opts else "")
        lines.append(f"```\n{usage}\n```\n")
        if opts:
            lines.append("| Option | Description |")
            lines.append("|---|---|")
            for o in opts:
                flags = ", ".join(f"`{f}`" for f in o.opts)
                lines.append(f"| {flags} | {(o.help or '').strip()} |")
            lines.append("")

    for name in sorted(root.commands):
        render(root.commands[name], [name], 2)
    return _page("CLI", "Every gaia command, generated from the Typer app.", "\n".join(lines))


def gen_commands() -> str:
    from gaia.commands import default_registry

    commands = sorted(default_registry().all(), key=lambda c: c.name)
    rows = [
        "Type these in any gaia chat (terminal, Telegram, WhatsApp). Some need a capability.\n",
        "| Command | Aliases | Usage | What it does | Requires |",
        "|---|---|---|---|---|",
    ]
    for c in commands:
        aliases = ", ".join(f"`/{a}`" for a in c.aliases) or "—"
        usage = f"`/{c.name} {c.usage}`" if c.usage else f"`/{c.name}`"
        cap = c.capability or "—"
        rows.append(f"| `/{c.name}` | {aliases} | {usage} | {c.summary} | {cap} |")
    return _page(
        "Chat commands", "The in-chat slash commands, from the command registry.", "\n".join(rows)
    )


def gen_config() -> str:
    from gaia.config.scaffold import render_default_yaml

    body = (
        "Gaia reads `~/.gaia/gaia.yaml` (hot-reloaded). Secrets live in `~/.gaia/.env`, never "
        "here. Inspect/edit with `gaia config get|set|edit`. The full commented default, generated "
        "from the schema:\n\n```yaml\n" + render_default_yaml().rstrip() + "\n```"
    )
    return _page("Config", "The gaia.yaml schema — the commented default, from the schema.", body)


def gen_tools() -> str:
    from gaia.tools.registry import default_registry

    registry = default_registry()
    rows = [
        "Tools are what gaia and its souls call to act. On by default; gated by "
        "`tools.<id>.enabled`. The model invokes these — you don't.\n",
        "| Tool | What it does |",
        "|---|---|",
    ]
    for name in registry.names():
        tool = registry.get(name)
        target = getattr(tool, "func", tool)
        doc = (inspect.getdoc(target) or "").strip().split("\n")[0]
        rows.append(f"| `{name}` | {doc} |")
    return _page(
        "Tools", "The tools gaia and its souls can call, from the tool registry.", "\n".join(rows)
    )


def main() -> None:
    REF_DIR.mkdir(parents=True, exist_ok=True)
    pages = {
        "cli.md": gen_cli(),
        "commands.md": gen_commands(),
        "config.md": gen_config(),
        "tools.md": gen_tools(),
    }
    for filename, content in pages.items():
        (REF_DIR / filename).write_text(content)
        print(f"wrote {REF_DIR / filename}")


if __name__ == "__main__":
    main()
